# Generated by Django 4.1.7 on 2023-02-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('gender', models.SmallIntegerField(choices=[(0, 'female'), (1, 'male')])),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_time', models.DateTimeField()),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.department')),
            ],
        ),
    ]
