# Generated by Django 4.1.7 on 2023-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_prettynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='prettynumber',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')], default=1),
        ),
    ]
