# Generated by Django 4.1.7 on 2023-03-04 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_admin_alter_prettynumber_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.SmallIntegerField(choices=[(1, 'Paid'), (0, 'Unpaid')], default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo')),
            ],
        ),
    ]
