# Generated by Django 4.1.7 on 2023-03-04 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_remove_order_user_order_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin'),
        ),
    ]
