# Generated by Django 4.1.7 on 2023-03-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_rename_ordernumber_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Number',
            new_name='number',
        ),
    ]
