# Generated by Django 4.1.7 on 2023-05-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.IntegerField()),
                ('airline_name', models.CharField(max_length=16)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_location', models.CharField(max_length=64)),
                ('arrival_location', models.CharField(max_length=64)),
                ('flight_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
