# Generated by Django 4.1.7 on 2023-05-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='seat_number',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
