# Generated by Django 4.1.7 on 2023-05-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_passenger_remove_order_title_order_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin',
        ),
    ]
