# Generated by Django 4.1.7 on 2023-05-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_platform', models.CharField(max_length=16)),
            ],
        ),
    ]
