# Generated by Django 4.1.7 on 2023-05-09 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.payment_method'),
        ),
    ]
